import type { CategoryKey, MailItem, Rule, SyncState } from "./types";

export const categories: CategoryKey[] = [
  "Important",
  "Finance / Bills",
  "Shopping / Orders",
  "Travel",
  "Work",
  "Personal",
  "Newsletters",
  "Security / Login Alerts",
  "Promotions",
  "Needs Reply",
  "Read Later",
  "Unknown / Review",
];

export const categoryColors: Record<CategoryKey, string> = {
  Important: "#ef4444",
  "Finance / Bills": "#0f766e",
  "Shopping / Orders": "#d97706",
  Travel: "#2563eb",
  Work: "#4f46e5",
  Personal: "#db2777",
  Newsletters: "#64748b",
  "Security / Login Alerts": "#b91c1c",
  Promotions: "#7c3aed",
  "Needs Reply": "#ea580c",
  "Read Later": "#0891b2",
  "Unknown / Review": "#475569",
};

export const initialSyncState: SyncState = {
  phase: "idle",
  imported: 186,
  total: 240,
  lastSync: "Today, 5:42 PM",
  message: "Mock Gmail import ready",
};

export const initialRules: Rule[] = [
  { id: "rule-bank", pattern: "bank, card, statement, bill", category: "Finance / Bills", hits: 42, enabled: true },
  { id: "rule-orders", pattern: "amazon, flipkart, delivered, invoice", category: "Shopping / Orders", hits: 31, enabled: true },
  { id: "rule-security", pattern: "login, password, verification, otp", category: "Security / Login Alerts", hits: 27, enabled: true },
  { id: "rule-travel", pattern: "flight, hotel, booking, itinerary", category: "Travel", hits: 13, enabled: true },
];

export const sampleEmails: MailItem[] = [
  {
    id: "msg-001",
    sender: "Google Security",
    email: "no-reply@accounts.google.com",
    subject: "New sign-in on Windows",
    snippet: "We noticed a new sign-in to your Google Account from Chrome on Windows. Review activity if this was not you.",
    receivedAt: "5:28 PM",
    category: "Security / Login Alerts",
    confidence: 96,
    unread: true,
    reason: "Security sender plus sign-in language matched the login alert rule.",
    labels: ["security", "login", "high confidence"],
  },
  {
    id: "msg-002",
    sender: "HDFC Bank",
    email: "alerts@hdfcbank.net",
    subject: "Credit card statement for May",
    snippet: "Your card statement is ready. Minimum amount due and payment date are included in the attached statement.",
    receivedAt: "4:44 PM",
    category: "Finance / Bills",
    confidence: 93,
    unread: true,
    reason: "Bank sender and statement keywords matched finance rules.",
    labels: ["bill", "card", "statement"],
  },
  {
    id: "msg-003",
    sender: "Amazon.in",
    email: "shipment-tracking@amazon.in",
    subject: "Your package is arriving tomorrow",
    snippet: "Track your order and delivery window. Your invoice is available in your account order history.",
    receivedAt: "3:16 PM",
    category: "Shopping / Orders",
    confidence: 91,
    unread: false,
    reason: "Marketplace sender plus package and invoice language.",
    labels: ["order", "delivery"],
  },
  {
    id: "msg-004",
    sender: "Priya Sharma",
    email: "priya@studio.example",
    subject: "Can you send the revised dashboard by tonight?",
    snippet: "The design review moved earlier. Please send the revised dashboard build and notes before the call.",
    receivedAt: "2:22 PM",
    category: "Needs Reply",
    confidence: 87,
    unread: true,
    reason: "Question phrasing and direct request indicate a likely reply is needed.",
    labels: ["reply", "work"],
  },
  {
    id: "msg-005",
    sender: "Render",
    email: "notifications@render.com",
    subject: "Deploy succeeded for inbox-service",
    snippet: "Your latest deploy finished successfully. View logs and service metrics from your Render dashboard.",
    receivedAt: "1:05 PM",
    category: "Work",
    confidence: 82,
    unread: false,
    reason: "Developer platform sender and deployment context matched work rules.",
    labels: ["deploy", "service"],
  },
  {
    id: "msg-006",
    sender: "IndiGo",
    email: "booking@goindigo.in",
    subject: "Your Bengaluru itinerary",
    snippet: "Your flight itinerary and web check-in details are ready. Carry a valid government ID.",
    receivedAt: "12:30 PM",
    category: "Travel",
    confidence: 89,
    unread: false,
    reason: "Itinerary and flight language matched travel rules.",
    labels: ["flight", "itinerary"],
  },
  {
    id: "msg-007",
    sender: "Figma",
    email: "team@figma.com",
    subject: "Weekly product updates",
    snippet: "Catch up on new collaboration features, prototypes, and design system improvements from this week.",
    receivedAt: "11:18 AM",
    category: "Newsletters",
    confidence: 78,
    unread: false,
    reason: "Digest-style subject and product update language matched newsletters.",
    labels: ["weekly", "digest"],
  },
  {
    id: "msg-008",
    sender: "Myntra",
    email: "offers@myntra.com",
    subject: "Extra 20% off ends tonight",
    snippet: "Your saved styles are now on sale. Use the code before midnight to unlock the discount.",
    receivedAt: "10:01 AM",
    category: "Promotions",
    confidence: 85,
    unread: false,
    reason: "Offer and discount language matched promotions.",
    labels: ["sale", "offer"],
  },
  {
    id: "msg-009",
    sender: "Aarav",
    email: "aarav@example.com",
    subject: "Dinner this weekend",
    snippet: "Are you free Saturday night? We can try the new place near Civil Lines.",
    receivedAt: "Yesterday",
    category: "Personal",
    confidence: 81,
    unread: false,
    reason: "Personal sender and casual scheduling language.",
    labels: ["personal"],
  },
  {
    id: "msg-010",
    sender: "Research Notes",
    email: "notes@papers.example",
    subject: "Long read: agent memory systems",
    snippet: "A saved article about memory retrieval, ranking, and user-controlled knowledge persistence.",
    receivedAt: "Yesterday",
    category: "Read Later",
    confidence: 74,
    unread: false,
    reason: "Long-form article pattern without urgent action.",
    labels: ["article", "read later"],
  },
];
